input_data_path: "data/raw/heart_disease.csv"
output_data_path: "data/processed/predict.csv"
output_model_path: "models/model.pkl"
feature_params:
  categorical_features:
    - "ca"
    - "cp"
    - "exang"
    - "fbs"
    - "restecg"
    - "sex"
    - "slope"
    - "thal"
  numerical_features:
    - "age"
    - "chol"
    - "oldpeak"
    - "thalach"
    - "trestbps"
  features_to_drop: []
  target_col: "condition"